---
- name: Grow partition
  command: "growpart /dev/sda 1"
  register: growpart
  ignore_errors: true

  #- name: Physical Volume resize
  #  command: "pvresize /dev/xvda3"
  #  register: pvresize
  #  when: growpart is succeeded
  #
  #- name: Logical Volume resize
  #  command: "lvresize -l +100%FREE /dev/mapper/rhel-root"
  #  register: lvresize
  #  when:
  #  - growpart is succeeded
  #  - pvresize is succeeded

- name: File system resize
  command: "xfs_growfs /"
  when:
  - growpart is succeeded
