---
ansible_user: ec2-user
ansible_become: yes
openshift_deployment_type: openshift-enterprise
openshift_release: v3.7
#openshift_image_tag: v3.7.0-0.189.0
#openshift_pkg_version: -3.7.0
#openshift_pkg_version: -3.5.5.26
#openshift_enable_service_catalog: false
#containerized: true

#openshift_disable_check:
#  - disk_availability
#  - memory_availability
#  - docker_storage
#  - docker_image_availability
openshift_check_min_host_disk_gb: 10
openshift_check_min_host_memory_gb: 3

osm_cluster_network_cidr: "10.1.0.0/16"
openshift_portal_net: "172.30.0.0/16"
osm_host_subnet_length: 9

openshift_docker_additional_registries:
  - registry.reg-aws.openshift.com

openshift_cockpit_deployer_prefix: registry.reg-aws.openshift.com:443/openshift3/

oreg_url: registry.reg-aws.openshift.com:443/openshift3/ose-${component}:${version}
oreg_auth_user: "{{ ansible_user_id }}"
# Get your token from the 'oc login' line at
# https://console.reg-aws.openshift.com/console/command-line
# Put your token in the file referenced below
oreg_auth_password: "{{ lookup('file', '~/oreg_auth_password.txt') }}"
