---
- name: Launch Playbook
  hosts: localhost
  connection: local
  gather_facts: no
  become: yes
  max_fail_percentage: 1

  tasks:
  - name: Start OpenShift VMs
    virt:
      name: "{{ hostvars[item].inventory_hostname_short }}"
      state: running
    with_items: "{{ groups.OSEv3 }}"

  - name: Wait for hosts to come online
    wait_for:
      host: "{{ hostvars[item].openshift_public_hostname }}"
      port: 22
      timeout: 120
    with_items: "{{ groups.OSEv3 }}"
