---
all:
  hosts:
    ec2-54-91-13-6.compute-1.amazonaws.com:
      openshift_ip: 172.18.7.107
      openshift_public_ip: 54.91.13.6
      openshift_hostname: ip-172-18-7-107.ec2.internal
      openshift_public_hostname: ec2-54-91-13-6.compute-1.amazonaws.com
      openshift_schedulable: False
    ec2-34-207-73-225.compute-1.amazonaws.com:
      openshift_ip: 172.18.3.222
      openshift_public_ip: 34.207.73.225
      openshift_hostname: ip-172-18-3-222.ec2.internal
      openshift_public_hostname: ec2-34-207-73-225.compute-1.amazonaws.com
      openshift_node_labels:
        region: infra
    ec2-52-201-251-14.compute-1.amazonaws.com:
      openshift_ip: 172.18.9.236
      openshift_public_ip: 52.201.251.14
      openshift_hostname: ip-172-18-9-236.ec2.internal
      openshift_public_hostname: ec2-52-201-251-14.compute-1.amazonaws.com
  children:
    masters:
      hosts:
        ec2-54-91-13-6.compute-1.amazonaws.com:
    nodes:
      hosts:
        ec2-54-91-13-6.compute-1.amazonaws.com:
        ec2-34-207-73-225.compute-1.amazonaws.com:
        ec2-52-201-251-14.compute-1.amazonaws.com:
    etcd:
      hosts:
        ec2-54-91-13-6.compute-1.amazonaws.com:
    OSEv3:
      children:
        masters:
        nodes:
        etcd:
