---
- name: Test Playbook
  hosts: nodes[1]
  connection: local
  gather_facts: false

  tasks:
  - debug:
      var: openshift_release

  - name: Convert openshift_release to a string
    set_fact:
      openshift_release: "{{ openshift_release | string }}"
    when:
    - openshift_release is defined
    - openshift_release | type_debug != 'unicode'

  - name: Remove leading 'v' from openshift_release
    set_fact:
      openshift_release: "{{ openshift_release[1:] }}"
    when:
    - openshift_release is defined
    - openshift_release[0] == 'v'

  - debug:
      var: openshift_release

  - name: Fail if we don't have a good version
    fail:
      msg: >
        Must define one of the following:
        - openshift_release
        - openshift_image_tag
        - openshift_pkg_version
    when:
#      - openshift_version is undefined


#- name: Validate node hostnames
#  hosts: nodes
#  tasks:
#
#  - name: Query DNS for IP address of {{ openshift_hostname }}
#    shell:
#      getent ahostsv4 {{ openshift_hostname }} | head -n 1 | awk '{ print $1 }'
#    register: lookupip
#    changed_when: false
#    failed_when: false
#
#  - name: Validate openshift_hostname when defined
#    fail:
#      msg: >
#        The hostname {{ openshift_hostname }} for {{ ansible_nodename }}
#        doesn't resolve to an IP address owned by this host. Please set
#        openshift_hostname variable to a hostname that when resolved on the host
#        in question resolves to an IP address matching an interface on this
#        host. This host will fail liveness checks for pods utilizing hostPorts.
#        See https://docs.openshift.org/latest/install_config/install/advanced_install.html#configuring-host-variables
#    when:
#    - lookupip.stdout != '127.0.0.1'
#    - lookupip.stdout not in ansible_all_ipv4_addresses
#    - not openshift_override_hostname_check | default(false)
#
#  - name: Validate openshift_ip exists on node when defined
#    fail:
#      msg: >
#        openshift_ip should be set to an IP of an interface on this node
#        Inventory setting: openshift_ip={{ openshift_ip }}
#        See https://docs.openshift.org/latest/install_config/install/advanced_install.html#configuring-host-variables
#    when:
#    - openshift_ip is defined
#    - openshift_ip not in ansible_all_ipv4_addresses


#- name: Test Playbook
#  hosts: localhost
#  connection: local
#  gather_facts: false
#  roles:
#  - installer_checkpoint
#
#  tasks:
#  - name: Set install initialization 'In Progress'
#    set_stats:
#      data:
#        installer_phase_initialize: "In Progress"
#        installer_phase_initialize_start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
#      aggregate: false
#
#  - pause:
#      seconds: 2
#
#  - name: Set install initialization 'Complete'
#    set_stats:
#      data:
#        installer_phase_initialize: "Complete"
#        installer_phase_initialize_end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
#      aggregate: false


#  - pause:
#      seconds: 2

#  - include_role:
#      name: test_role
#    static: no
#    when: False
#  - debug:
#      msg: "This is not in the role"
