- hosts: nodes
  gather_facts: no
  serial: "{{ nodes_serial | default(1) }}"
  max_fail_percentage: "{{ nodes_max_fail_percentage | default(0) }}"

  tasks:
  - debug:
      var: inventory_hostname
    failed_when: inventory_hostname == 'host12'

  - debug:
      msg: "Next task"

  - debug:
      msg: "Last task"


#    - name: Set fact openshift
#      set_fact:
#        openshift:
#          common:
#            hostname: "foo"
#
#    - name: Only show hosts that didn't fail
#      debug:
#        msg: "Setup ran!"
#      when:
#      - hostvars[item].openshift is defined
#      with_items: "{{ groups['nodes'] }}"
#      run_once: true
