---
- name: Create ssh bastion
  hosts: localhost
  connection: local

  vars:
    cluster_dir: "{{ lookup('env', 'OPT_CLUSTER_DIR') }}"
    kubeconfig_path: "{{ cluster_dir }}/assets/auth/kubeconfig"
    private_key_path: "{{ lookup('env', 'OPT_PRIVATE_KEY') | realpath }}"

  tasks:
  - name: Create ssh bastion namespace and secrets
    command: >
      oc apply -f -
      --config={{ kubeconfig_path }}
    register: oc_apply
    args:
      stdin: "{{ item.value | to_yaml }}"
    loop: "{{ ssh_bastion_resources | dict2items }}"
    changed_when:
    - ('created' in oc_apply.stdout) or
      ('configured' in oc_apply.stdout)
    vars:
      ssh_bastion_resources:
        namespace:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: byoh-ssh-bastion
        secrets:
          apiVersion: v1
          kind: Secret
          metadata:
            name: ssh-host-keys
            namespace: byoh-ssh-bastion
          data:
            ssh_host_rsa_key: "{{ lookup('file', private_key_path) | b64encode }}"
            sshd_config: "{{ lookup('file', 'files/ssh_bastion/sshd_config') | b64encode }}"

  - name: Create ssh bastion resources
    command: >
      oc apply -f files/ssh_bastion/
      --config={{ kubeconfig_path }}
    register: oc_apply
    changed_when:
    - ('created' in oc_apply.stdout) or
      ('configured' in oc_apply.stdout)

  - block:
    - name: Wait for ssh bastion deployment to rollout
      command: >
        oc get deployment.apps/ssh-bastion
        --config={{ kubeconfig_path }}
        --namespace=byoh-ssh-bastion
        --output=jsonpath='{.status.availableReplicas}'
      register: oc_get_deployment_replicas
      until:
      - oc_get_deployment_replicas.stdout | int > 0
      retries: 24
      delay: 5
      changed_when: false

    rescue:
    - name: DEBUG - Get ssh bastion pod name
      command: >
        oc get pods
        --config={{ kubeconfig_path }}
        --namespace=byoh-ssh-bastion
        --output=jsonpath='{.items[0].metadata.name}'
      register: ssh_bastion_pod
      changed_when: false

    - name: DEBUG - Get ssh bastion pod logs
      command: >
        oc describe pod/{{ ssh_bastion_pod.stdout }}
        --config={{ kubeconfig_path }}
        --namespace=byoh-ssh-bastion
      changed_when: false

    - name: DEBUG - ssh bastion deployment failed
      fail:
        msg: ssh bastion deployment failed
