---
- name: Add cloud-user if using Atomic nodes
  hosts: lb
  any_errors_fatal: true
  gather_facts: true
  remote_user: ec2-user
  become: yes
  become_method: sudo
  run_once: true
  vars:
    platform_type: "{{ lookup('env', 'OPT_PLATFORM_TYPE') | default('rhel') }}"
    ansible_user: ec2-user
    private_key_path: "{{ lookup('env', 'OPT_PRIVATE_KEY') | realpath }}"

  tasks:
  - name: Create cloud-user
    user:
      name: cloud-user
      shell: /bin/bash
      groups:
      - adm
      - wheel
      - systemd-journal

  - name: Ensure proper permissions on private key file
    file:
      path: "{{ private_key_path }}"
      mode: 0600

  - name: Create public key from private key file
    command: >
      ssh-keygen -f {{ private_key_path }} -y
    register: keygen_output

  - name: Add openshift-dev key
    authorized_key:
      user: cloud-user
      state: present
      key: "{{ keygen_output.stdout }}"

  - name: Modify sudoers
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%wheel\s'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
