---

- name: Terminate AWS instances
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    aws_region: us-east-1
    cluster_id: "{{ lookup('env', 'OPT_CLUSTER_ID') }}"
    cluster_dir: "{{ lookup('env', 'OPT_CLUSTER_DIR') }}"
    aws_instances_file: "{{ cluster_dir }}/inventory/aws.json"
    aws_lb_instance_file: "{{ cluster_dir }}/inventory/awslb.json"
    platform_type: "{{ lookup('env', 'OPT_PLATFORM_TYPE') | default('rhel') }}"

  tasks:
  - import_tasks: tasks/terminate.yml
    vars:
      aws_instance_file: "{{ aws_instances_file }}"
  - import_tasks: tasks/terminate.yml
    vars:
      aws_instance_file: "{{ aws_lb_instance_file }}"
    when: platform_type == 'atomic'
